# Generated by Django 5.0.2 on 2024-03-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Computer', 'Computer'), ('IT', 'IT'), ('Nursing', 'Nursing')], max_length=100),
        ),
    ]
