# Generated by Django 5.0.2 on 2024-03-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_customuser_email_alter_customuser_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='work_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
