# Generated by Django 5.0.2 on 2024-03-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_profile_work_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='images/doctor-icon.jpg', null=True, upload_to='photos/'),
        ),
    ]
