# Generated by Django 5.0.2 on 2024-03-24 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='doctor-icon.jpg', upload_to='photos/'),
        ),
        migrations.CreateModel(
            name='DeactivateAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('confirmation', models.CharField(help_text="Please type 'confirm' ", max_length=7)),
                ('deactivate_status', models.BooleanField(default=False)),
                ('create', models.DateTimeField(auto_now_add=True, help_text='Timestamp of creation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deactivate_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
